# Generated by Django 5.1.4 on 2025-01-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_remove_sensortype_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensortype',
            name='fields',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
