services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.django.prod
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings_production
      - ALLOWED_HOSTS=*
      - PYTHONUNBUFFERED=1
      - TOKEN_INFLUXDB=${TOKEN_INFLUXDB}
      - SECRET_KEY=acddce
    networks:
      - django_network
    volumes:
      - static_volume:/app/staticfiles  
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"  
    volumes:
      - static_volume:/app/staticfiles 
      - ./nginx.conf:/etc/nginx/nginx.conf 
    depends_on:
      - web
    networks:
      - django_network 
  mqtt:
    build:
      context: .
      dockerfile: Dockerfile.mqtt.prod
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_TOPIC=${MQTT_TOPIC}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    depends_on:
      - web
    networks:
      - django_network

networks:
  django_network:
    driver: bridge

volumes:
  static_volume: